<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable;CS4014;VSTHRD110;VSTHRD100</WarningsAsErrors>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataModel\MUnique.OpenMU.DataModel.csproj" />
    <ProjectReference Include="..\GameLogic\MUnique.OpenMU.GameLogic.csproj" />
    <ProjectReference Include="..\PlugIns\MUnique.OpenMU.PlugIns.csproj" />
  </ItemGroup>

</Project>
